spring:
  datasource:
    url: jdbc:mysql://mysql:3306/wg_base?useUnicode=true&characterEncoding=utf-8&&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver